### PR TITLE
explicitly link against OpenGL library, for deb13-amd64

### PR DESCRIPTION
**Pull request by dhorlick**
Building on deb13-amd64…

Before:
```sh
dhorlick@fublio:~/diy/forks/sim-arduboy$ make
MKDIR obj/obj-x86_64-linux-gnu
BUILD libsimavr
make[1]: Entering directory '/home/dhorlick/diy/forks/sim-arduboy/simavr/simavr'
CONF obj-x86_64-linux-gnu/cores.deps
CONF sim_core_decl.h
⋮
LD obj/obj-x86_64-linux-gnu/ssd1306_virt.o
/usr/bin/ld: obj/obj-x86_64-linux-gnu/ssd1306_gl.o: in function `ssd1306_gl_render':
/home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:67:(.text+0x15): undefined reference to `glClear'
/usr/bin/ld: /home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:78:(.text+0x57): undefined reference to `glMatrixMode'
/usr/bin/ld: /home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:80:(.text+0x5c): undefined reference to `glLoadIdentity'
/usr/bin/ld: /home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:81:(.text+0x8d): undefined reference to `glOrtho'
/usr/bin/ld: /home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:83:(.text+0xb3): undefined reference to `glScalef'
/usr/bin/ld: /home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:83:(.text+0xe2): undefined reference to `glScalef'
/usr/bin/ld: /home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:84:(.text+0xff): undefined reference to `glTranslatef'
/usr/bin/ld: /home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:88:(.text+0x109): undefined reference to `glEnable'
/usr/bin/ld: /home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:89:(.text+0x118): undefined reference to `glBlendFunc'
/usr/bin/ld: obj/obj-x86_64-linux-gnu/ssd1306_gl.o: in function `gl_set_bg_colour_':
/home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:44:(.text+0x16a): undefined reference to `glColor4f'
/usr/bin/ld: obj/obj-x86_64-linux-gnu/ssd1306_gl.o: in function `ssd1306_gl_render':
/home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:95:(.text+0x179): undefined reference to `glTranslatef'
/usr/bin/ld: /home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:97:(.text+0x183): undefined reference to `glBegin'
/usr/bin/ld: /home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:98:(.text+0x19e): undefined reference to `glVertex2f'
/usr/bin/ld: /home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:99:(.text+0x1aa): undefined reference to `glVertex2f'
/usr/bin/ld: /home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:100:(.text+0x1c5): undefined reference to `glVertex2f'
/usr/bin/ld: /home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:101:(.text+0x1f0): undefined reference to `glVertex2f'
/usr/bin/ld: obj/obj-x86_64-linux-gnu/ssd1306_gl.o: in function `gl_set_fg_colour_':
/home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:53:(.text+0x28b): undefined reference to `glColor4f'
/usr/bin/ld: obj/obj-x86_64-linux-gnu/ssd1306_gl.o: in function `ssd1306_gl_render':
/home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:109:(.text+0x2ae): undefined reference to `glVertex2f'
/usr/bin/ld: /home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:110:(.text+0x2be): undefined reference to `glVertex2f'
/usr/bin/ld: /home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:111:(.text+0x2cf): undefined reference to `glVertex2f'
/usr/bin/ld: /home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:112:(.text+0x2e9): undefined reference to `glVertex2f'
/usr/bin/ld: obj/obj-x86_64-linux-gnu/ssd1306_gl.o: in function `gl_set_fg_colour_':
/home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:55:(.text+0x346): undefined reference to `glColor4f'
/usr/bin/ld: obj/obj-x86_64-linux-gnu/ssd1306_gl.o: in function `ssd1306_gl_render':
/home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:83:(.text+0x353): undefined reference to `glScalef'
/usr/bin/ld: /home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:83:(.text+0x367): undefined reference to `glScalef'
/usr/bin/ld: obj/obj-x86_64-linux-gnu/ssd1306_gl.o: in function `gl_set_bg_colour_':
/home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:46:(.text+0x3ef): undefined reference to `glColor4f'
/usr/bin/ld: obj/obj-x86_64-linux-gnu/ssd1306_gl.o: in function `ssd1306_gl_render':
/home/dhorlick/diy/forks/sim-arduboy/./src/ssd1306_gl.c:119:(.text+0x3bd): undefined reference to `glEnd'
collect2: error: ld returned 1 exit status
make: *** [Makefile:84: obj/obj-x86_64-linux-gnu/sim_arduboy.elf] Error 1
```

After
```sh
dhorlick@fublio:~/diy/forks/sim-arduboy$ git apply patch.diff
dhorlick@fublio:~/diy/forks/sim-arduboy$ make
BUILD libsimavr
make[1]: Entering directory '/home/dhorlick/diy/forks/sim-arduboy/simavr/simavr'
make[1]: Nothing to be done for 'libsimavr'.
make[1]: Leaving directory '/home/dhorlick/diy/forks/sim-arduboy/simavr/simavr'
libsimavr done
LD obj/obj-x86_64-linux-gnu/ssd1306_virt.o
COPY obj/obj-x86_64-linux-gnu/sim_arduboy.elf to sim_arduboy
sim_arduboy done
```

For what it's worth, this _isn't_ necessary to build on Ubuntu 20.04.1 x86_64 (but the PR doesn't impact that build, either.)

Maybe something changed in Debian trixie?

### CODE REVIEW

**Comment by dxxb** [comment]
Merged, thank you!
